title = "Allan V.C. Quadros"
baseURL = "https://allanvc.github.io/"
theme = "hugo-researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = "UA-131372002-1"  # add your tracking id
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

# Enable comments by entering your Disqus shortname
disqusShortname = "allanvc"

[params]
  author = "Allan V.C. Quadros"
  description = "My personal website"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "Made with {pkgdown}, based on the Hugo Researcher theme"
    url = "https://github.com/ojroques/hugo-researcher"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "🏛︎"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Software"
    url = "/software"
    weight = 2
  [[menu.main]]
    name = "Posts"
    url = "/post"
    weight = 3
  [[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 4
  [[menu.main]]
    name = "Courses"
    url = "/courses"
    weight = 5
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 6

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
